kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demo-rolebinding
  namespace: dev
subjects:
- kind: ServiceAccount
  name: demo-sa
  namespace: dev
- kind: Group 
  name: system:serviceaccounts 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: demo-role
  apiGroup: rbac.authorization.k8s.io